### ISSUE TITLE
Support config_substitutions

### ISSUE THREAD

**Issue by simbabque** [frioux/Config-ZOMG#5]
I am using Config::ZOMG to load database config data in cronjobs that do backend maintenance work with my Catalyst project. In general that is fine, but in my unit test environment I am using [Catalyst::Plugin::ConfigLoader's `config_substitutions` feature](https://metacpan.org/pod/Catalyst::Plugin::ConfigLoader#config_substitutions-value) to get stuff from the environment through `__ENV(foo)__`.

I think it would make sense to support some of those substitutions to be a bit closer to Catalyst::Plugin::ConfigLoader. Of course not all of them make sense in a non-Catalyst environment, but some do:

- `__ENV(foo)__`
- `__literal(__FOO__)__`
- defining your own with a code reference

It would probably blow up the whole thing a bit and make it slower, but it might be worth looking into.

**Comment by frioux** [comment]
I'd consider documenting how to do this, but I absolutely would not make it work "for free" because it slows things down so much.  For what it's worth Config::JFDI already supports this.

**Comment by simbabque** [comment]
Oh, I didn't see that Config::JFDI supports it. My use-case is not the strongest though, and I found a solution where I don't need the ENV for those tests.

I think it would be possible to make it something that's off by default, or as a subclass that needs to be loaded explicitly. That way the cost would be minimized, and it won't break anyone's code. On the other hand, one can always do it oneself after loading, which is a bit messy, but would work.

Maybe a _Differences to Catalyst::Plugin::ConfigLoader_ or _... Config::JFDI_ section in the documentation that says this feature is not supported would be nice, though.

**Comment by frioux** [comment]
Yeah that's legit for sure.

-- 
sent from a rotary phone, pardon my brevity

**Comment by frioux** [comment]
Added a little bit of doc that describes this.  Will release at some point :)
